name: Code for Tucson
description: "Code for Tucson is a Code for America Brigade. The Code for America Brigade program is an international network of people committed to using their voices and hands, in collaboration with local governments, to make their cities better. Brigades build participatory power in their cities by holding regular civic hack nights and events, advocating for open data, and deploying apps. Brigades celebrate and share their successes with the Brigade network to further the global civic innovation movement."
markdown: kramdown

permalinks: pretty

collections:
   - projects

owner:
  name: Code for Tucson
  twitter:
  facebook:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

google_container_id: "GTM-NWHWNQ"
google_analytics: "UA-75440152-1"
google_verify:

sass:
  sass_dir: assets/_sass

baseurl: http://codefortucson.github.io/codefortucson-site
url: http://www.codefortucson.org
img_dir: assets/images

kramdown:
  parse_block_html: true

production: true
